# Python for (open) Neuroscience

_Lecture 1.1_ - More on `numpy`

Luigi Petrucco

Jean-Charles Mariani

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/vigji/python-cimec/blob/main/lectures/Lecture1.1_Numpy.ipynb)

## More on `numpy` functions

### `np.mean()` / `np.nanmean()`

Calculate the average of an array, either global or along some axis:

In [152]:
import numpy as np
arr = np.random.randint(0, 255, (5, 6))
mean = np.mean(arr)  # compute the mean of the whole array

print(f"{arr};\nmean: {mean}")

[[ 48 170  87 127  88  92]
 [126  85 182 253 219  67]
 [179 117 230 149 114 213]
 [ 59 169 190 128  57  91]
 [ 17  78 184 143 249 174]];
mean: 136.16666666666666


If we want to take the average along a specific dimension, we can pass the axis as a parameter:

In [153]:
import numpy as np
arr = np.random.randint(0, 255, (5, 6))
arr_mean = np.mean(arr, axis=0)  # we specify one axis along which to mean

print(f"{arr};\nmean: {arr_mean}")

[[115 113 217 184  32  17]
 [176 185  35 109  93 150]
 [192 247 125  95 170  70]
 [166 212 141 105 182 143]
 [ 20 213   7  80 189  32]];
mean: [133.8 194.  105.  114.6 133.2  82.4]


If there are nan values around, we have to use `np.nanmean()`:

In [154]:
import numpy as np

# we need a float dtype to use nan values:
arr = np.random.randint(0, 255, (5, 6)).astype(float) 

arr[0, 0] = np.nan
arr_mean = np.mean(arr)  # regular mean
arr_nan_mean = np.nanmean(arr)  # use nanmean

print(f"{arr};\nregular mean: {arr_mean}\nnanmean: {arr_nan_mean}")

[[ nan  88. 227.  96. 128. 145.]
 [143. 199.  86. 221.  50.  14.]
 [195.  15. 189. 184.  31. 133.]
 [ 21. 194.  83. 185.  35. 218.]
 [143. 237. 100. 168.  56.  82.]];
regular mean: nan
nanmean: 126.41379310344827


Many of the functions we're about to see behave in this way - assume they have a nan-dealing equivalent!

 - `np.std()` / `np.nanstd()`
 - `np.percentile()` / `np.nanpercentile()`
 - `np.max()` / `np.nanmax()`
 - ...

### `np.std()` / `np.nanstd()`

Calculate the standard deviation of an array, either global or along some axis:

In [23]:
arr = np.random.normal(0, 3, 1000)
np.std(arr)

2.9911940005367863

### `np.median()` / `np.nanmedian()`

Calculate the median of an array, either global or along some axis:

In [27]:
arr = np.random.randint(0, 100, (1000, 10))
np.median(arr, axis=0)

array([51., 49., 49., 49., 51., 50., 49., 47., 49., 53.])

### `np.max()` / `np.min()`

Calculate the minimum or maximum of an array, either global or along some axis:

In [28]:
arr = np.random.randint(0, 100, 1000)

np.min(arr), np.max(arr)  # print min and max together

(0, 99)

### `np.percentile()`

Calculate a given percentile of an array, either global or along some axis:

In [29]:
arr = np.random.randint(0, 1000, 10000)

np.percentile(arr, 75)  # print min and max together

756.0

### `np.unique()`

Return unique values of an array, and if asked their counts

In [33]:
np.unique(np.array([1, 2, 2, 3, 3, 3]))

array([1, 2, 3])

In [35]:
# If we ask we can get counts as well
unique_values, counts = np.unique([1,2,2,3], return_counts=True) 

print("unique:", unique_values)

print("counts:", counts)

unique: [1 2 3]
counts: [1 2 1]


In [36]:
arr = np.random.normal(0, 1, 1000000)

### `np.diff()` / `np.cumsum()`  

We can compute cumulative sums (integrals) of an array with `np.cumsum()`:

In [39]:
my_arr = np.array([[1,2,3,4],[1,2,4,5]])
np.cumsum(my_arr, axis=0)

array([[1, 2, 3, 4],
       [2, 4, 7, 9]])

We can compute differences between consecutive elements of an array using `np.diff()`:

In [40]:
my_arr = np.array([1,2,3,4])
np.diff(my_arr)

array([1, 1, 1])

(Practicals 1.1.0)

### Write code the `numpy` way

When operating with matrices, you should always aim at writing <span style="color:indianred">vectorized</span> code

Vectorized code: code where for loops are replaced by operations over matrix dimensions

An very simple example: vectors multiplication

In [41]:
vector_1 = np.random.normal(0, 1, (10000000,))
vector_2 = np.random.normal(0, 1, (10000000,))

In [42]:
%%timeit
product = np.zeros(vector_1.shape)  # initialize empty result vector

# Compute the multiplication in a loop:
for i in range(vector_1.shape[0]):
    product[i] = vector_1[i] * vector_2[i]

1.54 s ± 26.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [43]:
%%timeit
product = vector_1 * vector_2

7.77 ms ± 21.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Another example: Z-score the rows of a matrix:

In [44]:
data_matrix = np.random.randint(0, 255, (100000, 100))

In [45]:
%%timeit
normalized_matrix = np.zeros(data_matrix.shape)  # start an empty matrix of matching shape 

# Loop over rows (first dimension), take mean and std, subtract and divide:
for i in range(data_matrix.shape[0]):
    row_mean = np.mean(data_matrix[i, :])
    row_std = np.std(data_matrix[i, :])
    
    normalized_matrix[i, :] = (data_matrix[i, :] - row_mean) / row_std

1.38 s ± 5.46 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [48]:
%%timeit
rows_mean = np.mean(data_matrix, axis=1)  # vectorized mean
rows_std = np.std(data_matrix, axis=1)  # vectorized std

# Write the normalization as a vector operation.
# Note how we use broadcasting to make sure the right dimensions are propagated!

normalized_matrix = data_matrix - rows_mean[:, np.newaxis] / rows_std[:, np.newaxis]

In [59]:
rows_mean[:, None].T

array([[135.01, 125.87, 126.52, ..., 122.23, 130.12, 123.72]])

In [49]:
rows_mean.shape

(100000,)

## Search indexes

Some functions find indexes of the elements of an array that match some criterion.

### `np.argmin()` / `np.argmax()` 

Find the position of the maximum or the minimum of an array

In [60]:
arr = np.array([5,  0, 2, 9, 6,])

np.argmin(arr)  # give index of smallest element

1

In [61]:
np.argmax(arr)  # give index of biggest element

3

For a multi-dimensional array:

In [90]:
arr = np.array([[5, 1, 2], 
                [3, 0, 4]])
print(arr)
np.argmin(arr)

[[5 1 2]
 [3 0 4]]


4

What is this number 4?

## Flat indexing

When you have a multi-dimensional array, you can always index it in two ways:
 - the standard, multi-dimensional indexing (e.g., `my_array[3,4]`)
 - with **flat indexing**: we index the array after flattening it out in a single dimension

In [4]:
# Example:
my_arr = np.random.randint(0, 10, (4, 3))
my_arr

array([[8, 3, 1],
       [8, 2, 9],
       [9, 1, 1],
       [5, 5, 8]])

There is a flatten representation of this array that we can look at with `.flatten()` method we saw in the last lecture:

In [10]:
import numpy as np
# When we flatten, we concatenate all values of the matrix in a single dimension.
# We keep the order of the dimensions of the matrix (the first 3 elements are the first row, that
# is, the first dimension):
print(my_arr)
min_idx = np.argmin(my_arr)
print(min_idx)
my_arr.flatten()[min_idx]


[[8 3 1]
 [8 2 9]
 [9 1 1]
 [5 5 8]]
2


1

The number we got from `np.argmax()` is the number we would need to use over the flattened representation of the array to get the maximum value!

In [118]:
max_idx = np.argmax(my_arr)  # get max index
print(max_idx)

flat_array = my_arr.flatten()  # create a flattened array
flat_array[max_idx]

2


7

One last thing. it is obviously annoying having to create a new flattened array to use the index. Also, we create a duplicated array in memory - not good.

The best way to use this indexing it through the `.flat` representation of the matrix:

In [117]:
my_arr.flat[max_idx]

7

### Index raveling / unraveling

To convert the flat index to a tuple of matrix indexes, we can use `np.unravel_index()`:

In [124]:
arr = np.array([[5, 1, 2], [3, 3, 0]])
idx = np.argmin(arr)

# unravel index takes an index of the flattened array, and the shape of the matrix,
# and give us the tuple of ordinary indexes that correspond to that flat index.
np.unravel_index(idx, arr.shape)  

(1, 2)

This is an illustration of what happens. Flat indexes (_left_) are converted to tuple indexes (_right_):
(there is a bug in the image, last value should be 11!)

![unravel illustration](https://i.stack.imgur.com/sxwBU.png)

The converse operation, called unravel, can be done with `np.ravel_multi_index()`, and it goes from the right representation to the left one:

In [125]:
np.ravel_multi_index((1, 1), arr.shape)

4

### `np.nonzero()` / `np.argwhere()`

There are functions that allow us to get the index of all True elements in an array. In this way, we can set a condition (_e.g._, values above a threshold), and find the index of all elements satisfying it!

#### `np.argwhere()`

`np.argwhere()` find `True` elements and gives us a `(n_pts, n_matrix_dims)` shaped array of indexes:

In [12]:
arr = np.array([[1, 2, 3, 4, 5], 
                [0, 5, 0, 3, 1],
                [0, 6, 7, 4, 1]])  # define an array
boolean_vals = arr > 2  # boolean condition
print("Original array:")

print(arr)
print("\nBoolean array:")
print(boolean_vals)

Original array:
[[1 2 3 4 5]
 [0 5 0 3 1]
 [0 6 7 4 1]]

Boolean array:
[[False False  True  True  True]
 [False  True False  True False]
 [False  True  True  True False]]


In [13]:
indexes = np.argwhere(boolean_vals)
print("\nTrue elements indexes:")
print(indexes)


True elements indexes:
[[0 2]
 [0 3]
 [0 4]
 [1 1]
 [1 3]
 [2 1]
 [2 2]
 [2 3]]


The indexes matrix has one row for every True value, and each column represents the position of that value on the boolean matrix.

#### `np.nonzero()`

`np.nonzero()` is very similar to `np.argwhere()`, but instead of a single matrix of indexes (with each column representing the indexes over one dimension for all points), it returns us a tuple of arrays. 

That is to say, each one of those arrays corresponds to a column of the indexes array returned by `np.argwhere()`.

In [14]:
# print("\nBoolean array:")
#print(boolean_vals)

indexes_tuple = np.nonzero(boolean_vals)
# print("\nTrue elements indexes:")
print(indexes_tuple)

(array([0, 0, 0, 1, 1, 2, 2, 2]), array([2, 3, 4, 1, 3, 1, 2, 3]))


indexes_tuples is a tuple of arrays; each one of thise array corresponds to a column in the indexes matrix above!

In [141]:
indexes_tuple[0] == indexes[:, 0]

array([ True,  True,  True,  True,  True,  True,  True,  True])

Why is it useful to return a tuple of arrays?

### Array indexes are tuples!

Whenever you are writing something like:

In [142]:
arr[0, 1]

2

You are actually passing a tuple into the square brackets! If you remember, in python, comma separated
values with no brakets are automatically put together in a tuple:

In [143]:
a = 1, 2
type(a)

tuple

So, writing `arr[0, 1]` is literally the same as writing `arr[(0, 1)]`:

In [144]:
arr[(0, 1)]

2

If you remember, you can pass arrays instead of single numbers for indexing:

In [150]:
# This code will retrieve three elements from arr:
#   - the element in (0, 2)
#   - the element in (1, 3)
#   - the element in (1, 1)

print(arr)
print("\nSelected items:")
arr[np.array([0, 1, 1]), np.array([2, 3, 1])]

[[1 2 3 4 5]
 [0 5 0 3 1]
 [0 6 7 4 1]]

Selected items:


array([3, 3, 5])

Therefore, we can directly use the indexes arrays tuple we get from `np.nonzero()` to retrieve all elements of the original matrix that matched the boolean condition!

In [16]:
arr = np.array([[1, 2, 3, 4, 5], 
                [0, 5, 0, 3, 1],
                [0, 6, 7, 4, 1]])
boolean_vals = arr > 2
print("Original array:")
print(arr)
print("\nBoolean array:")
print(boolean_vals)

indexes_tuple = np.nonzero(boolean_vals)
indexes_tuple

Original array:
[[1 2 3 4 5]
 [0 5 0 3 1]
 [0 6 7 4 1]]

Boolean array:
[[False False  True  True  True]
 [False  True False  True False]
 [False  True  True  True False]]


(array([0, 0, 0, 1, 1, 2, 2, 2]), array([2, 3, 4, 1, 3, 1, 2, 3]))

In [17]:
filtered_values = arr[indexes_tuple]  # here we directly use the tuple to index the array!
print("\nElements bigger than 2:")
print(filtered_values)


Elements bigger than 2:
[3 4 5 5 3 6 7 4]


(Practicals 1.1.1)